version: '3'
# services:
#   rails:
#     build:
#       context: .
#       dockerfile: ./docker/Dockerfile-server
#     ports:
#       - "8080:8080"
#     volumes:
#       - .:/home/app/campusflora
#     environment:
#       - RAILS_SERVE_STATIC_FILES=true
#     env_file:
#       - .env/development/database
#       - .env/development/web
#   mysql:
#     image: mysql:5.7
#     env_file:
#       - .env/development/database
#     volumes:
#       - db_data:/var/lib/mysql
# volumes:
#   db_data:
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5at2=e9=424Ig<#%P2ov2j103Y2eL
      MYSQL_DATABASE: campusflora
      MYSQL_USER: campusflora
      MYSQL_PASSWORD: "@U%?38k&#~j)<0J36(4=T9(?h<u(V"
      # DATABASE_HOST: localhost
    ports:
      - "3307:3306"
    volumes_from:
      - mysqldata
  mysqldata:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile-mysql-data
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    command: bundle exec rails s -p 3000 -b '13.239.16.175'
    volumes:
      - ".:/project"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: campusflora
      DB_NAME: campusflora
      DB_PASSWORD: "@U%?38k&#~j)<0J36(4=T9(?h<u(V"
      DB_HOST: localhost