version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app/campusflora
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    env_file:
      - .env/development/database
      - .env/development/web
  mysql:
    image: mysql:5.7
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
# services:
#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: project
#       MYSQL_USER: projectuser
#       MYSQL_PASSWORD: password
#     ports:
#       - "3307:3306"
#   app:
#     build:
#       context: .
#       dockerfile: ./docker/Dockerfile-server
#     command: bundle exec rails s -p 3000 -b '13.239.16.175'
#     volumes:
#       - ".:/project"
#     ports:
#       - "3001:3000"
#     depends_on:
#       - db
#     links:
#       - db
#     environment:
#       DB_USER: root
#       DB_NAME: project
#       DB_PASSWORD: password
#       DB_HOST: db